#include "gpio_config.h"
#include "stm32f3xx.h"

#define GPIO_AFRL_AFRL0_AF1 		(0x1UL << (0U))
#define GPIO_AFRL_AFRL1_AF1			(0x1UL << (4U))
#define GPIO_AFRL_AFRL2_AF1			(0x1UL << (8U))
#define GPIO_AFRL_AFRL3_AF1			(0x1UL << (12U))

#define GPIO_AFRH_AFRH8_AF6			(0x6UL << (0U))
#define GPIO_AFRH_AFRH9_AF6			(0x6UL << (4U))
#define GPIO_AFRH_AFRH10_AF6		(0x6UL << (8U))
#define GPIO_AFRH_AFRH11_AF11		(0xBUL << (12U))

#define GPIO_AFRL_AFRL4_AF2 		(0x2UL << (16U))
#define GPIO_AFRL_AFRL5_AF2			(0x2UL << (20U))

#define GPIO_AFRL_AFRL6_AF2			(0x2UL << (24U))
#define GPIO_AFRL_AFRL7_AF2			(0x2UL << (28U))

Status_t GpioInit(void)
{
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	RCC->AHBENR |= RCC_AHBENR_GPIOBEN;

	GPIOA->MODER |= GPIO_MODER_MODER0_1;
	GPIOA->MODER |= GPIO_MODER_MODER1_1;
	GPIOA->MODER |= GPIO_MODER_MODER2_1;
	GPIOA->MODER |= GPIO_MODER_MODER3_1;

	GPIOA->MODER |= GPIO_MODER_MODER8_1;
	GPIOA->MODER |= GPIO_MODER_MODER9_1;
	GPIOA->MODER |= GPIO_MODER_MODER10_1;
	GPIOA->MODER |= GPIO_MODER_MODER11_1;

	GPIOB->MODER |= GPIO_MODER_MODER4_1;
	GPIOB->MODER |= GPIO_MODER_MODER5_1;

	GPIOB->MODER |= GPIO_MODER_MODER6_1;
	GPIOB->MODER |= GPIO_MODER_MODER7_1;

	GPIOA->AFR[0] |= GPIO_AFRL_AFRL0_AF1;
	GPIOA->AFR[0] |= GPIO_AFRL_AFRL1_AF1;
	GPIOA->AFR[0] |= GPIO_AFRL_AFRL2_AF1;
	GPIOA->AFR[0] |= GPIO_AFRL_AFRL3_AF1;

	GPIOA->AFR[1] |= GPIO_AFRH_AFRH8_AF6;
	GPIOA->AFR[1] |= GPIO_AFRH_AFRH9_AF6;
	GPIOA->AFR[1] |= GPIO_AFRH_AFRH10_AF6;
	GPIOA->AFR[1] |= GPIO_AFRH_AFRH11_AF11;

	GPIOB->AFR[0] |= GPIO_AFRL_AFRL4_AF2;
	GPIOB->AFR[0] |= GPIO_AFRL_AFRL5_AF2;

	GPIOB->AFR[0] |= GPIO_AFRL_AFRL6_AF2;
	GPIOB->AFR[0] |= GPIO_AFRL_AFRL7_AF2;

	GPIOB->OTYPER |= GPIO_OTYPER_OT_4;
	GPIOB->OTYPER |= GPIO_OTYPER_OT_5;

	GPIOB->OTYPER |= GPIO_OTYPER_OT_6;
	GPIOB->OTYPER |= GPIO_OTYPER_OT_7;

	GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPDR4_0);


	return STATUS_OK;
}
